# 应用服务 WEB 访问端口
server.port=8080
spring.datasource.url=jdbc:mysql://192.168.6.140:8009/AllSchoolAPI?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.username=weiensong
spring.datasource.password=weiensong.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
